---
# tasks file for ajsalminen.drupal_basic
- name: Create settings.php.
  template:
    src: "{{ drupal_basic_settings_template }}"
    dest: "{{ drupal_basic_site_dir}}/{{drupal_basic_webroot_subdir}}/sites/default/settings.php"
  when: drupal_basic_create_settings
  
- include: permissions.yml tags=permissions