---
# tasks file for ajsalminen.drupal_basic
- name: Create settings.php.
  template:
    src: drupal7-settings.php.j2
    dest: "{{ drupal_basic_site_dir}}/www/sites/default/settings.php"
  when: drupal_basic_create_settings